### ISSUE TITLE
GridFS capability

### ISSUE THREAD

**Issue by flipxfx** [spohlenz/mongomodel#34]
Are there any plans to interface with GridFS or is there anyway to do it currently?

**Comment by spohlenz** [comment]
I do not currently have any plans to implement GridFS support. However I would happily accept a pull request adding support for it.

My next priority is to update the version of the mongo Ruby driver used to the latest version, which I am working on now. If you wish to take a look at GridFS support, then you may want to wait for the next release (hopefully in the next week).

**Comment by flipxfx** [comment]
Ok. We ended up just using the mongo driver directly for now 😄
